### ISSUE TITLE
ClassCastException in IntelliJ IDEA 2024.2.1 Preview

### ISSUE THREAD

**Issue by sdrzazga-nsd** [apple/pkl-intellij#60]
IntelliJ IDEA 2024.2.1 Preview (Ultimate Edition)
Build #IU-242.21829.15, built on August 14, 2024
Runtime version: 21.0.3+13-b509.11 x86_64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Non-Bundled Plugins:
  org.pkl (0.30.0)

```
java.lang.ClassCastException: class com.intellij.psi.impl.source.PsiJavaFileImpl cannot be cast to class org.pkl.intellij.psi.PklModule (com.intellij.psi.impl.source.PsiJavaFileImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @676a639d; org.pkl.intellij.psi.PklModule is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @14b37491)
	at org.pkl.intellij.psi.ExtensionsKt.getEnclosingModule(Extensions.kt:62)
	at org.pkl.intellij.PklTypeDeclarationProvider.getSymbolTypeDeclarations(PklTypeDeclarationProvider.kt:29)
	at com.intellij.codeInsight.navigation.impl.GttdKt.typeElements(gttd.kt:131)
	at com.intellij.codeInsight.navigation.impl.GttdKt.access$typeElements(gttd.kt:1)
	at com.intellij.codeInsight.navigation.impl.GttdKt$typeSymbols$2.invokeSuspend(gttd.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at com.intellij.codeInsight.navigation.impl.GTTDActionData.result(gttd.kt:67)
	at com.intellij.codeInsight.navigation.actions.GotoTypeDeclarationHandler2.invoke$lambda$1$lambda$0(GotoTypeDeclarationHandler2.kt:31)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.kt:321)
	at com.intellij.codeInsight.navigation.actions.GotoTypeDeclarationHandler2.invoke$lambda$1(GotoTypeDeclarationHandler2.kt:29)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$3(AnyThreadWriteThreadingSupport.kt:219)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:264)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.underModalProgress$lambda$1(ActionUtil.kt:267)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.underModalProgress$lambda$2(ActionUtil.kt:268)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:299)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:567)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:85)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:501)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by bioball** [comment]
Thanks for the report! Submitted https://github.com/apple/pkl-intellij/pull/61 to fix.
